# Generated by Django 4.0.4 on 2022-05-18 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizadores', '0003_alter_organizador_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizador',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizador', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
