# Generated by Django 4.0.4 on 2022-04-23 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bairros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('zona', models.CharField(choices=[('C', 'Centro'), ('N', 'Norte'), ('S', 'Sul'), ('L', 'Leste'), ('O', 'Oeste')], default=('N', 'Norte'), max_length=10)),
            ],
            options={
                'verbose_name': 'Bairro',
                'verbose_name_plural': 'Bairros',
                'ordering': ['nome'],
                'unique_together': {('nome',)},
            },
        ),
    ]
