# Generated by Django 4.0.4 on 2022-04-23 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bairros', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bairros',
            new_name='Bairro',
        ),
    ]
