# Generated by Django 4.0.4 on 2022-04-30 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logradouros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(auto_created=True, default=True, verbose_name='Usuário Ativo')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('sobrenome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sobrenome')),
                ('cpf', models.CharField(max_length=15, unique=True, verbose_name='CPF')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-mail')),
                ('celular', models.CharField(blank=True, max_length=14, null=True, verbose_name='Celular')),
                ('data_criacao', models.DateTimeField(auto_now=True, verbose_name='Data de Criação')),
                ('logradouro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logradouros', to='logradouros.logradouro', verbose_name='Logradouro')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': ['nome'],
                'unique_together': {('cpf',)},
            },
        ),
    ]
