# Generated by Django 4.0.4 on 2022-04-30 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logradouros', '0001_initial'),
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='logradouro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logradouros', to='logradouros.logradouro', verbose_name='Logradouro'),
        ),
    ]
