# Generated by Django 4.0.4 on 2022-05-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_pessoa_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='primeiro_acesso',
            field=models.BooleanField(auto_created=True, default=True, verbose_name='Primero acesso'),
        ),
    ]
