# Generated by Django 4.0.4 on 2022-05-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotas', '0002_alter_cota_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cota',
            name='numero',
            field=models.IntegerField(verbose_name='Número'),
        ),
    ]
