# Generated by Django 4.0.4 on 2022-05-15 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='GrupoPermission',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
