# Generated by Django 4.0.4 on 2022-05-07 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_grupopermission_permission_tipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
