# Generated by Django 4.0.4 on 2022-05-07 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_permission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
