# Generated by Django 4.0.4 on 2022-05-09 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupopermission',
            options={'verbose_name': 'Permissão', 'verbose_name_plural': 'Permissões'},
        ),
    ]
