# Generated by Django 4.0.4 on 2022-04-30 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('rifas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bilhete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('cotas', models.CharField(max_length=100, verbose_name='Cotas')),
                ('pago', models.BooleanField(verbose_name='Pago')),
                ('premiado', models.BooleanField(verbose_name='Premiado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cliente', to='clientes.cliente', verbose_name='Cliente')),
                ('rifa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bilhete', to='rifas.rifa', verbose_name='Rifa')),
            ],
            options={
                'verbose_name': 'Bilhete',
                'verbose_name_plural': 'Bilhetes',
                'ordering': ['pk'],
            },
        ),
    ]
