# Generated by Django 4.0.4 on 2022-05-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilhetes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilhete',
            name='pago',
            field=models.BooleanField(auto_created=True, default=False, verbose_name='Pago'),
        ),
        migrations.AlterField(
            model_name='bilhete',
            name='premiado',
            field=models.BooleanField(auto_created=True, default=False, verbose_name='Premiado'),
        ),
    ]
