# Generated by Django 4.0.4 on 2022-05-05 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bilhetes', '0002_alter_bilhete_pago_alter_bilhete_premiado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bilhete',
            old_name='numero',
            new_name='valor',
        ),
    ]
