# Generated by Django 4.0.4 on 2022-05-05 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bilhetes', '0003_rename_numero_bilhete_valor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bilhete',
            old_name='valor',
            new_name='numero',
        ),
    ]
