# Generated by Django 4.0.4 on 2022-04-30 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0001_initial'),
        ('itens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rifa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='rifa', to='rifas.rifa', verbose_name='Rifa'),
            preserve_default=False,
        ),
    ]
