# Generated by Django 4.0.4 on 2022-04-30 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Data de criação')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('cotas', models.IntegerField(verbose_name='Cotas')),
                ('valor_cota', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor da cota')),
                ('data_sorteio', models.DateField(verbose_name='Data do sorteio')),
                ('regulamento', models.TextField(blank=True, null=True)),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organizador', to='organizadores.organizador', verbose_name='Organizador')),
            ],
            options={
                'verbose_name': 'Rifa',
                'verbose_name_plural': 'Rifas',
                'ordering': ['titulo'],
            },
        ),
    ]
