# Generated by Django 4.0.4 on 2022-05-18 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logradouros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logradouro',
            name='endereco',
            field=models.CharField(max_length=200, verbose_name='Endereço'),
        ),
    ]
