# Generated by Django 4.0.4 on 2022-04-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logradouros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logradouro',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='logradouro',
            name='numero',
            field=models.CharField(max_length=6, verbose_name='Número'),
        ),
    ]
